### ISSUE TITLE
Is it possible to mock dojox/form/Uploader?

### ISSUE THREAD

**Issue by ridoo** [dojo/dojox#304]
I have set up a request mock, registering URLs with dedicated response data in my intern test setup as [suggested in a blog post](https://www.sitepen.com/blog/2014/07/14/mocking-data-with-intern/). 

However, as far I understand `Uploader` does not use `dojo/request` so the recommended solution does not work as intended. Is there a similar solution how to mock uploading a file? In my case it is an external API which I do not want to spam with test files.

I use Dojo `v1.11`

**Comment by dylans** [comment]
File uploads are one thing you cannot truly mock as file uploads are typically a write-only API. You could mock the interface for file uploads, but not the actual file itself.

**Comment by ridoo** [comment]
okay thanks @dylans .. the API I am uploading to provides a simple REST endpoint for doing so. It returns some metadata which I have to use after upload succeeds to perform further logic. Therefore I was wondering if I could test that kind of workflow without using the API directly.

Obviously, I will have to refactor my interface then to be testable. Thanks anyway!
