### ISSUE TITLE
Please open a Security Advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [dojo/dojox#313]
Hi,

I believe I've found a security vulnerability. Please open a security advisory and add me to it so we can discuss it.
https://github.com/dojo/dojox/security/advisories

**Comment by nicknisi** [comment]
Hi @JLLeitschuh I have opened an advisory for further discussion and invited you to it. Thanks!

**Comment by JLLeitschuh** [comment]
That was this one. It's already resolved. 😆 We're all good here.
https://github.com/dojo/dojox/security/advisories/GHSA-pg97-ww7h-5mjr
