### ISSUE TITLE
dojox/mobile/Switch border radius empty string issue

### ISSUE THREAD

**Issue by dylans** [dojo/dojox#323]
Reported via email:

Found a bug in Dojo 1.16.1 mobile Switch.js as shown below (with the code patched to work). What happens is that the borderTopLeftRadius is an empty string and that results in the size being NaN values, and then the browser throws an exception due to invalid SVG being injected from:

```
		_createMaskImage: function(){
			if(this._timer){
				 this._timer.remove();
				 delete this._timer;
			}
			if(this._hasMaskImage){ return; }
			var w = domStyle.get(this.domNode,"width"), h = domStyle.get(this.domNode,"height");
			this._width = (w - domStyle.get(this.knob,"width"));
			this._hasMaskImage = true;
			if(!(has("mask-image"))){ return; }
			var rDef = domStyle.get(this.left, "borderTopLeftRadius");
			if(!rDef /*CM FIX 2020-04-14*/ || rDef == "0px"){ return; }
			var rDefs = rDef.split(" ");
			var rx = parseFloat(rDefs[0]), ry = (rDefs.length == 1) ? rx : parseFloat(rDefs[1]);

// CM 2020-04-14: what is the point of the line of code just below?
// [commented out] var id = (this.shape+"Mask"+w+h+rx+ry).replace(/\./,"_");

			// CM Optimize 2020-04-14
if ( rx && ry )
{ maskUtils.createRoundMask(this.switchNode, 0, 0, 0, 0, w, h, rx, ry, 1); }
		},

```

The exception occurs in "Chrome" engine on Android 6 during startup of a page, when there is a resizeAll() method being called after parsing an HTML page that has Dojo switches in views, before everything is shown (that should be visible)...

**Comment by msssk** [comment]
These changes make sense to me. I'm not sure under what conditions `domStyle.get()` would return an empty string for a property, but I trust the existence of those conditions is what prompted this bug report.

The `id` variable is indeed unused and pointless.

While unlikely, it is possible for a border radius to be set to a pair, one of which is 0, which has the same effect as both being zero, so the check for `if(rx && ry)` makes sense.
